name: simple_app
description: "A new Flutter project with Terra cleanup features."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Firebase
  firebase_core: ^3.8.0
  
  # State Management
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.5
  
  # Code Generation
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  
  # Utilities
  uuid: ^4.3.3
  
  # Routing
  go_router: ^14.2.0
  
  # UI Enhancement Libraries
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.2
  glassmorphism: ^3.0.0
  rive: ^0.12.4
  lottie: ^3.0.0
  shimmer: ^3.0.0
  flutter_svg: ^2.0.9
  
  # Image handling
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7
  
  # Maps & Location
  google_maps_flutter: ^2.5.3
  geolocator: ^11.0.0
  permission_handler: ^11.3.0
  
  # Other utilities
  url_launcher: ^6.2.5
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.9
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/badges/
    - assets/images/
    - assets/icons/